// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Grid: typeof import('./../components/grid.vue')['default']
    Undefined: typeof import('./../components/index.vue')['default']
  }
}

export { }
